version: '3.8'

services:
  navbar:
    build: ./frontend/navbar
    ports:
      - "3001:80"
    volumes:
      - ./frontend/navbar/src:/app/src
      - ./frontend/navbar/static:/app/static
      - ./frontend/navbar/dist:/app/dist

  main-menu:
    build: ./frontend/main-menu
    ports:
      - "3002:80"
    volumes:
      - ./frontend/main-menu/src:/app/src
      - ./frontend/main-menu/static:/app/static
      - ./frontend/main-menu/dist:/app/dist

  3d-engine:
    build: ./frontend/3d-engine
    ports:
      - "3003:80"
    volumes:
      - ./frontend/3d-engine/src:/app/src
      - ./frontend/3d-engine/static:/app/static
      - ./frontend/3d-engine/dist:/app/dist

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./backend/auth-service:/app

  data-service:
    build: ./backend/data-service
    ports:
      - "8002:8000"
    volumes:
      - ./backend/data-service:/app

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/app
=======
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map NGINX port 80 to host port 8080
    volumes:
      - ./frontend:/app
      - /app/dist
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map backend port 8000 to host port 8000
    volumes:
      - ./backend:/app
    environment:
      - DENO_ENV=development
    restart: always
