version: '3.8'

services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:80"
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/public:/app/public
      - ./apps/frontend/dist:/app/dist
      - ./apps/frontend/src/index.html:/usr/share/nginx/html/index.html

  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app

  shared-ui:
    build: ./apps/shared-ui
    ports:
      - "3004:80"
    volumes:
      - ./apps/shared-ui/src:/app/src
      - ./apps/shared-ui/dist:/app/dist

  shared-utils:
    build: ./apps/shared-utils
    ports:
      - "3005:80"
    volumes:
      - ./apps/shared-utils/src:/app/src
      - ./apps/shared-utils/dist:/app/dist

  gateway:
    build: ./gateway
    ports:
      - "8001:8000"
    volumes:
      - ./gateway:/app
