version: '3.8'

services:
  navbar:
    build: ./microfrontends/frontend-auth
    ports:
      - "3001:80"
    volumes:
      - ./microfrontends/frontend-auth/src:/app/src
      - ./microfrontends/frontend-auth/static:/app/static
      - ./microfrontends/frontend-auth/dist:/app/dist

  main-menu:
    build: ./microfrontends/frontend-dashboard
    ports:
      - "3002:80"
    volumes:
      - ./microfrontends/frontend-dashboard/src:/app/src
      - ./microfrontends/frontend-dashboard/static:/app/static
      - ./microfrontends/frontend-dashboard/dist:/app/dist

  3d-engine:
    build: ./frontend/3d-engine
    ports:
      - "3003:80"
    volumes:
      - ./frontend/3d-engine/src:/app/src
      - ./frontend/3d-engine/static:/app/static
      - ./frontend/3d-engine/dist:/app/dist

  auth-service:
    build: ./backend-auth
    ports:
      - "8001:8000"
    volumes:
      - ./backend-auth:/app

  data-service:
    build: ./backend-data
    ports:
      - "8002:8000"
    volumes:
      - ./backend-data:/app

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/app
