version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map NGINX port 80 to host port 8080
    volumes:
      - ./frontend:/app
      - /app/dist
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map backend port 8000 to host port 8000
    volumes:
      - ./backend:/app
    environment:
      - DENO_ENV=development
    restart: always
